{
 "title": "TradeSystem",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "mysql" },
   { "name": "database", "label": "Database", "query": "tradesystem" },
   {
    "name": "playereconomyfilter",
    "label": "Player Economy Filter",
    "query": "SELECT DISTINCT(type) FROM ${database}.trade_metrics WHERE $__timeFilter(date) AND category LIKE \"economy\""
   },
   {
    "name": "playerFilter",
    "label": "Player Filter",
    "query": "SELECT name FROM ${database}.trade_players\nUNION\nSELECT player1 FROM ${database}.tradelog\nUNION\nSELECT player2 FROM ${database}.tradelog"
   }
  ]
 },
 "panels": [
  {
   "title": "Avg. trading duration",
   "type": "stat",
   "description": "The average duration of trades that were cancelled OR finished.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    AVG(TIME_TO_SEC(TIMEDIFF(\r\n        t.timestamp, \r\n        (\r\n            SELECT timestamp \r\n            FROM ${database}.tradelog \r\n            WHERE timestamp <= t.timestamp AND t.player1 = player1 AND t.player2 = player2 AND message LIKE \"Trade started\" \r\n            ORDER BY timestamp DESC \r\n            LIMIT 1\r\n        )\r\n    ))) as duration\r\nFROM ${database}.tradelog as t\r\nWHERE $__timeFilter(t.timestamp) AND message IN (\"Trade cancelled\", \"Trade finished\") AND (LENGTH(\"$playerFilter\") = 2 OR player1 REGEXP \"${playerFilter:regex}\" OR player2 REGEXP \"${playerFilter:regex}\")"
    }
   ]
  },
  {
   "title": "Avg. finish duration",
   "type": "stat",
   "description": "The average duration of trades that were finished.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    AVG(TIME_TO_SEC(TIMEDIFF(\r\n        t.timestamp, \r\n        (\r\n            SELECT timestamp \r\n            FROM ${database}.tradelog \r\n            WHERE timestamp <= t.timestamp AND t.player1 = player1 AND t.player2 = player2 AND message LIKE \"Trade started\" \r\n            ORDER BY timestamp DESC \r\n            LIMIT 1\r\n        )\r\n    ))) as duration\r\nFROM ${database}.tradelog as t\r\nWHERE $__timeFilter(t.timestamp) AND message LIKE \"Trade finished\" AND (LENGTH(\"$playerFilter\") = 2 OR player1 REGEXP \"${playerFilter:regex}\" OR player2 REGEXP \"${playerFilter:regex}\")"
    }
   ]
  },
  {
   "title": "Avg. cancel duration",
   "type": "stat",
   "description": "The average duration of trades that were cancelled.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    AVG(TIME_TO_SEC(TIMEDIFF(\r\n        t.timestamp, \r\n        (\r\n            SELECT timestamp \r\n            FROM ${database}.tradelog \r\n            WHERE timestamp <= t.timestamp AND t.player1 = player1 AND t.player2 = player2 AND message LIKE \"Trade started\" \r\n            ORDER BY timestamp DESC \r\n            LIMIT 1\r\n        )\r\n    ))) as duration\r\nFROM ${database}.tradelog as t\r\nWHERE $__timeFilter(t.timestamp) AND message LIKE \"Trade cancelled\" AND (LENGTH(\"$playerFilter\") = 2 OR player1 REGEXP \"${playerFilter:regex}\" OR player2 REGEXP \"${playerFilter:regex}\")"
    }
   ]
  },
  {
   "title": "Trades started",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "WITH RECURSIVE series AS (\r\n    SELECT\r\n        0 as value,\r\n        $__timeFrom() as timestamp\r\n    UNION ALL\r\n    SELECT\r\n        0 as value,\r\n        TIMESTAMPADD(MINUTE, 5, timestamp)\r\n    FROM series\r\n    WHERE\r\n        timestamp <= CAST($__timeTo() AS DATETIME)\r\n)\r\nSELECT (series.value + IFNULL(nested.value, 0)) as \"#Trades started\", $__timeGroup(series.timestamp,'5m') as time\r\nFROM series \r\nLEFT JOIN (\r\n    SELECT SUM(1) as value, timestamp \r\n    FROM ${database}.tradelog \r\n    WHERE message LIKE \"Trade started\" AND (LENGTH(\"$playerFilter\") = 2 OR player1 REGEXP \"${playerFilter:regex}\" OR player2 REGEXP \"${playerFilter:regex}\")\r\n    GROUP BY $__timeGroup(timestamp,'5m')\r\n) AS nested \r\nON $__timeGroup(series.timestamp,'5m') = $__timeGroup(nested.timestamp,'5m') \r\nGROUP BY $__timeGroup(series.timestamp,'5m')"
    }
   ]
  },
  {
   "title": "Most traded items",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT type, SUM(quantity) AS amount\r\nFROM ${database}.trade_metrics AS m\r\nLEFT JOIN ${database}.trade_players AS p ON m.sender = p.id\r\nWHERE $__timeFilter(date) AND category LIKE \"item\" AND (LENGTH(\"$playerFilter\") = 2 OR name REGEXP \"${playerFilter:regex}\")\r\nGROUP BY type\r\nORDER BY quantity DESC"
    }
   ]
  },
  {
   "title": "Most traded economy",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    type,\r\n    SUM(\r\n        CASE \r\n            WHEN type = 'Exp level icon' THEN\r\n                CASE \r\n                    WHEN quantity < 353 THEN SQRT(quantity + 9) - 3\r\n                    WHEN quantity < 1508 THEN 8.1 + SQRT(0.4 * (quantity - 195.975))\r\n                    ELSE 325 / 18 + SQRT(2 / 9 * (quantity - 54215 / 72))\r\n                END\r\n            ELSE quantity\r\n        END\r\n    ) AS amount\r\nFROM ${database}.trade_metrics AS m\r\nLEFT JOIN ${database}.trade_players AS p ON m.sender = p.id\r\nWHERE $__timeFilter(date) AND category LIKE 'economy' AND (LENGTH(\"$playerFilter\") = 2 OR name REGEXP \"${playerFilter:regex}\")\r\nGROUP BY type;\r\n"
    }
   ]
  },
  {
   "title": "Current trades",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "WITH RECURSIVE series AS (\r\n  SELECT\r\n    0 as value,\r\n    $__timeFrom() as timestamp\r\n  UNION\r\n  ALL\r\n  SELECT\r\n    0 as value,\r\n    TIMESTAMPADD(MINUTE, 5, timestamp)\r\n  FROM\r\n    series\r\n  WHERE\r\n    timestamp <= CAST($__timeTo() AS DATETIME)\r\n)\r\nSELECT\r\n  (series.value + IFNULL(nested.value, 0)) as \"#Trades cancelled\",\r\n  $__timeGroup(series.timestamp, '5m') as time\r\nFROM\r\n  series\r\n  LEFT JOIN (\r\n    SELECT\r\n      SUM(1) as value,\r\n      timestamp\r\n    FROM\r\n      ${database}.tradelog\r\n    WHERE\r\n      message LIKE \"Trade cancelled\"\r\n      AND (\r\n        LENGTH(\"$playerFilter\") = 2\r\n        OR player1 REGEXP \"${playerFilter:regex}\"\r\n        OR player2 REGEXP \"${playerFilter:regex}\"\r\n      )\r\n    GROUP BY\r\n      $__timeGroup(timestamp, '5m')\r\n  ) AS nested ON $__timeGroup(series.timestamp, '5m') = $__timeGroup(nested.timestamp, '5m')\r\nGROUP BY\r\n  $__timeGroup(series.timestamp, '5m')"
    },
    {
     "rawSql": "WITH RECURSIVE series AS (\r\n  SELECT\r\n    0 as value,\r\n    $__timeFrom() as timestamp\r\n  UNION\r\n  ALL\r\n  SELECT\r\n    0 as value,\r\n    TIMESTAMPADD(MINUTE, 5, timestamp)\r\n  FROM\r\n    series\r\n  WHERE\r\n    timestamp <= CAST($__timeTo() AS DATETIME)\r\n)\r\nSELECT\r\n  (series.value + IFNULL(nested.value, 0)) as \"#Trades finished\",\r\n  $__timeGroup(series.timestamp, '5m') as time\r\nFROM\r\n  series\r\n  LEFT JOIN (\r\n    SELECT\r\n      SUM(1) as value,\r\n      timestamp\r\n    FROM\r\n      ${database}.tradelog\r\n    WHERE\r\n      message LIKE \"Trade finished\"\r\n      AND (\r\n        LENGTH(\"$playerFilter\") = 2\r\n        OR player1 REGEXP \"${playerFilter:regex}\"\r\n        OR player2 REGEXP \"${playerFilter:regex}\"\r\n      )\r\n    GROUP BY\r\n      $__timeGroup(timestamp, '5m')\r\n  ) AS nested ON $__timeGroup(series.timestamp, '5m') = $__timeGroup(nested.timestamp, '5m')\r\nGROUP BY\r\n  $__timeGroup(series.timestamp, '5m')"
    }
   ]
  },
  {
   "title": "Cancel/Finish ratio",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tradesystem",
     "rawSql": "SELECT IF(message LIKE \"Trade finished\", \"Trades finished\", \"Trades cancelled\"), COUNT(*) as value \r\nFROM ${database}.tradelog \r\nWHERE $__timeFilter(timestamp) AND (message LIKE \"Trade finished\" OR message LIKE \"Trade cancelled\") AND (LENGTH(\"$playerFilter\") = 2 OR player1 REGEXP \"${playerFilter:regex}\" OR player2 REGEXP \"${playerFilter:regex}\")\r\nGROUP BY message"
    }
   ]
  },
  {
   "title": "Most trading players (items, offering)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT name as player, uuid, type as item, SUM(quantity) as amount, IFNULL(specification, \"{}\") as specification\r\nFROM ${database}.trade_metrics as m \r\nLEFT JOIN ${database}.trade_players as p ON m.sender = p.id \r\nWHERE $__timeFilter(date) AND category LIKE \"item\" AND (LENGTH(\"$playerFilter\") = 2 OR name REGEXP \"${playerFilter:regex}\")\r\nGROUP BY sender, type, specification\r\nORDER BY SUM(quantity) DESC, name ASC, type ASC\r\nLIMIT 15"
    }
   ]
  },
  {
   "title": "Trading worlds (offering)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(sender_world, IF(sender_server IS NULL, \"\", CONCAT(\" (\", sender_server, \")\"))) AS world, SUM(1) as value\r\nFROM ${database}.trade_metrics AS m\r\nLEFT JOIN ${database}.trade_players AS p ON m.sender = p.id\r\nWHERE $__timeFilter(date) AND (LENGTH(\"$playerFilter\") = 2 OR name REGEXP \"${playerFilter:regex}\")\r\nGROUP BY sender_server, sender_world"
    }
   ]
  },
  {
   "title": "Trading worlds (receiving)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(receiver_world, IF(receiver_server IS NULL, \"\", CONCAT(\" (\", receiver_server, \")\"))) AS world, SUM(1) as value\r\nFROM ${database}.trade_metrics AS m\r\nLEFT JOIN ${database}.trade_players AS p ON m.receiver = p.id\r\nWHERE $__timeFilter(date) AND (LENGTH(\"$playerFilter\") = 2 OR name REGEXP \"${playerFilter:regex}\")\r\nGROUP BY receiver_server, receiver_world"
    }
   ]
  },
  {
   "title": "Trading servers (offering)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT IFNULL(sender_server, \"bukkit\") AS server, SUM(1) as value\r\nFROM ${database}.trade_metrics AS m\r\nLEFT JOIN ${database}.trade_players AS p ON m.sender = p.id\r\nWHERE $__timeFilter(date) AND (LENGTH(\"$playerFilter\") = 2 OR name REGEXP \"${playerFilter:regex}\")\r\nGROUP BY sender_server"
    }
   ]
  },
  {
   "title": "Trading servers (receiving)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT IFNULL(receiver_server, \"bukkit\") AS server, SUM(1) as value\r\nFROM ${database}.trade_metrics AS m\r\nLEFT JOIN ${database}.trade_players AS p ON m.sender = p.id\r\nWHERE $__timeFilter(date) AND (LENGTH(\"$playerFilter\") = 2 OR name REGEXP \"${playerFilter:regex}\")\r\nGROUP BY receiver_server"
    }
   ]
  },
  {
   "title": "Most trading players (economy, offering)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT name as player, uuid, type, \r\n    IF(${playereconomyfilter} LIKE \"#included in trades\", \r\n        COUNT(*), \r\n        SUM(\r\n            CASE \r\n                WHEN type = 'Exp level icon' THEN\r\n                    CASE \r\n                        WHEN quantity < 353 THEN SQRT(quantity + 9) - 3\r\n                        WHEN quantity < 1508 THEN 8.1 + SQRT(0.4 * (quantity - 195.975))\r\n                        ELSE 325 / 18 + SQRT(2 / 9 * (quantity - 54215 / 72))\r\n                    END\r\n                ELSE quantity\r\n            END\r\n        )\r\n    ) as ${playereconomyfilter},\r\n    CASE \r\n        WHEN ${playereconomyfilter} LIKE \"Exp level icon\" THEN\r\n            \"#levels traded\"\r\n        WHEN ${playereconomyfilter} LIKE \"#included in trades\" THEN\r\n            \"The number of trades that include offers with this economy type.\"\r\n        ELSE \"-\"\r\n    END as \"description\"\r\nFROM ${database}.trade_metrics as m \r\nLEFT JOIN ${database}.trade_players as p ON m.sender = p.id \r\nWHERE $__timeFilter(date) AND category LIKE \"economy\" AND (LENGTH(\"$playerFilter\") = 2 OR name REGEXP \"${playerFilter:regex}\")\r\nGROUP BY sender, type\r\nORDER BY SUM(quantity) DESC\r\nLIMIT 15"
    }
   ]
  }
 ]
}